sudo: required
services:
  - docker

before_install:
  - docker build -t renaldekoker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run renaldekoker/react-test npm test -- --coverage

after_success:
  - docker build -t renaldekoker/multi-client ./client
  - docker build -t renaldekoker/multi-nginx ./nginx
  - docker build -t renaldekoker/multi-server ./server
  - docker build -t renaldekoker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push renaldekoker/multi-client
  - docker push renaldekoker/multi-nginx
  - docker push renaldekoker/multi-server
  - docker push renaldekoker/multi-worker
#
#deploy:
  #provider: elasticbeanstalk
  #region: us-east-2
  #app: multi-docker
  #env: Multidocker-env
  #bucket_name: elasticbeanstalk-us-east-2-466583602716
  #bucket_path: docker-multi
  #on:
    #branch: master
  #access_key_id:
    3secure: $AWS_ACCESS_KEY
  #secret_access_key:
    #secure: $AWS_SECRET_KEY